### ISSUE TITLE
Experimental Replication

### ISSUE THREAD

**Issue by zixuWang2022** [Khaos2022/Khaos-master#1]
Hi~！
I have read your paper and I would now like to ask a few questions about experimental reproduction. In testing how Khaos specified the files for Fission and Fusion on SPEC CPU 2006/2017, SPEC CPU contains multiple files per benchmark. 
Looking forward to your response.

**Comment by Khaos2022** [comment]
Hi!
We modified the config files in the `SPEC/config` folder. For example, the fufi.ori mode can be set as

## fufi.ori.cfg
- ext           = fufi.ori
...
- CC=/path_to_Khaos/build/bin/clang -flto -fuse-ld=lld /path_to_Khaos/build/lib/fusion_helper.o

- CXX=/path_to_Khaos/build/bin/clang++ -flto -fuse-ld=lld /path_to_Khaos/build/lib/fusion_helper.o
...

- OPTIMIZATION     = -O2 -mllvm -enable-fis    -mllvm -enable-fus  -mllvm -ori -fno-discard-value-names -w
...

- OPTIMIZE     = -O2 -mllvm -enable-fis    -mllvm -enable-fus  -mllvm -ori -fno-discard-value-names -w
...

Note: The `-flto -fuse-ld=lld` should be used when using fusion. Please copy the `fusion_helper.o` to your build path. 

Best!
